## Pull from existing image
# FROM nvcr.io/nvidia/pytorch:24.07-py3
FROM continuumio/miniconda3

## Copy requirements
COPY ./src/requirements.txt .

## Install Python packages in Docker image
RUN pip3 install -r requirements.txt

## Copy all files
COPY ./ ./

## Execute the inference command 
CMD ["./src/run_inference_t2.py"]
ENTRYPOINT ["python3"]